import { StyleSheet,Platform } from "react-native";

const styles = createStyles();
export default styles;

function createStyles() {
    return StyleSheet.create({
      h1: {
        fontSize: 25,
        margin: 10,
      },
      h2: {
        fontSize: 20,
        margin: 10,
      },
      button: {backgroundColor: 'black',borderRadius:4, height: 50, padding: 10,justifyContent:'center',alignContentContent:'center'},
      plusbutton: {backgroundColor: 'black',borderRadius:4,marginRight: 10, marginLeft: 10, justifyContent:'center',alignContentContent:'center', padding: 10},
      minusbutton: {backgroundColor: 'red',borderRadius:4,marginRight: 10, marginLeft: 10, justifyContent:'center',alignContentContent:'center', padding:10},
      nobutton: {backgroundColor: 'gray',borderRadius:4,marginRight: 10, marginLeft: 10, justifyContent:'center',alignContentContent:'center', padding:10},
      plusMinusText: {color: 'white', fontSize: 20, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' },
      buttonText: {color: 'white', fontSize:15},
      role: {marginLeft: 10},
      name: {marginLeft: 10},
      container: {
        flex: 1,
        flexGrow: 1,
        backgroundColor: 'white',
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        padding: 5,
      },
      choice: {flexDirection:'row', alignItems: 'left',padding: 5, alignContent: 'center'},
      choiceText: {fontSize:30},
      inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        padding: 10,
        width: '100%',
        maxWidth: 1024,
        marginHorizontal: 'auto',
        pointerEvents: 'auto',
      },
      domainContainer : {
        flexDirection: 'column',
      },
      input: {
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 5,
        padding: 10,
        marginRight: 10,
        fontSize: 18,
        color: 'gray',
        height: 50,
      },
      chooseButton: {
        backgroundColor: 'black',
        borderRadius: 5,
        padding: 10,
        margin: 5,
        width: 300,
      },
      addButton: {
        backgroundColor: 'black',
        borderRadius: 5,
        padding: 10,
        marginRight: 5,
      },
      addButtonText: {
        fontSize: 18,
        color: 'white',
      },
      todoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 4,
        padding: 10,
        borderBottomColor: 'gray',
        borderBottomWidth: 1,
        width: '100%',
        maxWidth: 1024,
        marginHorizontal: 'auto',
        pointerEvents: 'auto',
      },
      todoText: {
        flex: 1,
        fontSize: 18,
        fontFamily: 'Inter_500Medium',
        color: 'black',
      },
      instructions: {
        margin: 5,
      },
      dropdownButtonStyle: {
        width: '95%',
        height: 50,
        backgroundColor: '#E9ECEF',
        borderRadius: 12,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 12,
        marginBottom: 5,
        borderWidth: 2,
        borderColor: 'black',
        width: '70%',
      },
      dropdownButtonTxtStyle: {
        flex: 1,
        fontSize: 18,
        fontWeight: '500',
        color: '#151E26',
      },
      dropdownButtonArrowStyle: {
        fontSize: 28,
      },
      dropdownButtonIconStyle: {
        fontSize: 28,
        marginRight: 8,
      },
      dropdownMenuStyle: {
        backgroundColor: '#E9ECEF',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'black',
      },
      dropdownItemStyle: {
        width: '100%',
        flexDirection: 'row',
        paddingHorizontal: 12,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 8,
      },
      dropdownItemTxtStyle: {
        flex: 1,
        fontSize: 18,
        fontWeight: '500',
        color: '#151E26',
      },
      dropdownItemIconStyle: {
        fontSize: 28,
        marginRight: 8,
      },
      footer: {
        backgroundColor: 'white',
        marginLeft: 5,
        marginRight: 5,
        padding: 5,
        borderWidth: 1,
        borderColor: 'black',
      },
    })
  }